### PR TITLE
inearbyint: add scalar implementation based on _mm_cvtss_si32

### PR DESCRIPTION
**Pull request by timblechmann**

### CODE REVIEW

**Comment by jfalcou** [comment]
Looks good to me. Tim, did you want to add anything or can we proceed to merge ?

**Comment by timblechmann** [comment]
feel free to merge!

**Comment by jtlap** [comment]
Hello Tim,
I have seen the issue by not the pull request ! (sorry)
So I have done the same job and I have benched the function

::- Compiler: GNU C++ version 6.2.0 20160901
::- Platform: linux
::- SIMD:     boost::simd::sse4_2_
 Benchmarking results for: "scalar_inearbyint"
      Size          Result       Unit       Stat         Samples     Generators 
         1         13.8968      (cpe)   (median)           48367    rand<float>[-10, 10]
         1         15.2414      (cpe)   (median)           48794    rand<double>[-10, 10]

: Benchmarking results for: "scalar_fast_inearbyint"
      Size   Result       Unit       Stat         Samples      Generators 
         1         1.48981      (cpe)   (median)           59271        rand<float>[-10, 10]  
         1         11.3097      (cpe)   (median)           52691      rand<double>[-10, 10]

I have also written a non fast version that takes into account the bad values returned by the intrinsics at nan and inf. The cost is 1.2 cycle for adding the 2 tests so far better than the pure scalar version:

...
      if (BOOST_UNLIKELY(is_nan(a0))) return Zero<A0>();
      if (BOOST_UNLIKELY(a0 == Inf<A0>())) return Valmax<A0>();
      return _mm_cvtss_si32(_mm_set_ss(a0));
...

::: Benchmarking results for: "scalar_inearbyint"
      Size          Result       Unit       Stat         Samples          Generators 
         1         2.69119      (cpe)   (median)           60415     rand<float>[-10, 10]
         1          14.874      (cpe)   (median)           48620      rand<double>[-10, 10]

::: Benchmarking results for: "scalar_fast_inearbyint"
      Size          Result       Unit       Stat         Samples          Generators 
         1         1.45735      (cpe)   (median)           58519    rand<float>[-10, 10]
         1         10.7766      (cpe)   (median)           53390     rand<double>[-10, 10]

I have also added the bench file. 

I will probably make an other pull request if you don't mind

**Comment by jtlap** [comment]
I think I will also add a call through _mm_cvtsd_si64 in scalar with sse2, the gain is similar.

**Comment by jfalcou** [comment]
@timblechmann Would you check if jtlap branch satisfy your need and thus I'll merge the branch

**Comment by timblechmann** [comment]
had a quick look ... looks good to me!

**Pull request closed without merging**
