### PR TITLE
Propagate the declval adaptation made for dispatch to simd.

### PR DESCRIPTION
**Pull request by aminiussi**
If the support gnu lib is too old, switch declval to boost.

### CODE REVIEW

**Comment by jfalcou** [comment]
Shouldn't it be bd::detail everywhere ? or did you forgot a boost/simd/detail file ?

**Comment by aminiussi** [comment]
I used the bd::detail.
An alternative would be to import the declval patch into the simd namespace. Not sure which one is best.

**Comment by aminiussi** [comment]
Just noticed something weird with all_reduce.hpp, passed the test though... 
I'll update that.

**Comment by aminiussi** [comment]
I suspect that the correspondng result_t using directives are not execised which is why the test passed.

**Pull request merged**
