### PR TITLE
Nested varaidic templates are an issue for intel15

### PR DESCRIPTION
**Pull request by aminiussi**
similar to #431

### CODE REVIEW

**Comment by aminiussi** [comment]
Pending on #435

**Comment by aminiussi** [comment]
Pending on #435

**Comment by aminiussi** [comment]
Provided I got rebase right

**Comment by aminiussi** [comment]
One of the test timed out, but I don't think I can re-lauch it (unless I do a fake commit),

**Comment by jfalcou** [comment]
I restarted it

**Pull request merged**
