### PR TITLE
any and none (but not all) where buggy in sse4.1 because of -0.0(f)

### PR DESCRIPTION
**Pull request by jtlap**

### CODE REVIEW

**Comment by jfalcou** [comment]
can you assess effects on performances of functions using any as horizontl selectors ?

**Comment by jtlap** [comment]
not yet, I will this afternoon. But I advise to merge to suppress the bug, and I will see to a better modification if possible

**Comment by jfalcou** [comment]
i'm more enclined we do the job in one single piece becaue we'll just forget about this and scratch our head later. any and nne are rtaher fundamental so let's bench, see and merge if it's OK or find another solution before merging.

**Comment by jtlap** [comment]
I tested with abs the bench is quite 0.5 cycle better than the mere common version. So I propose to merge except if you have a better solution.

**Comment by jfalcou** [comment]
The question is how worse it is compared to the old version ?

**Comment by jtlap** [comment]
20%
float 0.5 -> 0.6
double 1 ->1.2

of course the old version is buggy...

**Pull request merged**
