### PR TITLE
Nsm namespace

### PR DESCRIPTION
**Pull request by aminiussi**
Mv nsm in boost. Since simd is destined to go to boost and it requires nsm, it probably belong here. Maybe nsm should be spitted in int a few file and have it's own lib/directory ? From there, some configuration should become easier or more straightforward.

### CODE REVIEW

**Comment by aminiussi** [comment]
Could not get rid of spurious commits dd0cee0 and 	fa7c847 despite the fact there is only an empty line...
Still not getting rebase I'm afraid...

**Comment by jfalcou** [comment]
did you rebased from an uptdate local develop branch ?
Also i a commit ends up empty, rebase should tell you you can git rebase --skip it.

Next to that, not sure the move is significant. There's precedent for bosot library with non-boost detail component.

**Comment by aminiussi** [comment]
I did rebase from my develop branch those upstream is numscale/develop. I tried rebasing on numscale/develop with no clear improvement. I'm gonna look at the rebase command more closely...

Could you point me to one of those non-boost detail components, I'd like to see how they did it. 
My issue is with the naming scope, I need to select some type_traits symbols from std or boost depending on the value of **BOOST_DISPATCH_INCOMPLETE_STD** and nsm uses some of those symbols. Since _nsm_  'precedes' both boost.simd and boost.dispatch, that would imply renaming **BOOST_DISPATCH_INCOMPLETE_STD** into **NSM_INCOMPLETE_STD**, putting corresponding bit of configuration currently in boost/simd/detail/dispatch/config.hpp into   boost/simd/detail/nsm.hpp (since the whole nsm component is in a single file, it seems unnatural to associate it with a config file) which implies putting nsm.hpp everywhere (since it then becomes, de facto, a config file) and adding a type_traits namespace into nsm.
Is that correct ?

**Comment by aminiussi** [comment]
Think I got the rebase ! 
Ok, through brute force...

**Note**:  just read the "don't do that" section :-1: No one pulled that hopefully...

**Comment by jfalcou** [comment]
OK 2 points:  

 - I'll try to grab a file separated NSM and put it there

 - Isn't the INCOMPLETE_STD flag be something completely even in boost/config.hpp ?

**Comment by aminiussi** [comment]
Not sure I got the 2nd point, I'd certainly like to have such a flag in boost/config.hpp.
Actually, most configuration is made based on 
**#if defined(BOOST_INTEL_GCC_VERSION) && (BOOST_INTEL_GCC_VERSION < 40600)**
which uses a single variable already in boost and maybe just as explicit as **BOOST_INCOMPLETE_STD**. I don't think the current issue will appear in another configuration anyway.

Let me know

**Comment by jfalcou** [comment]
My idea was to move cnfig related issues ot boost/config.hpp
Now I can see why you don't really want to duplicate this.

**Comment by aminiussi** [comment]
This PR is mostly made irrelevant by #389 #382.

**Pull request closed without merging**
