### PR TITLE
Intel warning

### PR DESCRIPTION
**Pull request by aminiussi**
two local variable names masks globals names. While not illegal or problematic per se, it generates very long warnings with intel -Wall.
One of those var, sign, was not used.

### CODE REVIEW

**Comment by jfalcou** [comment]
would mind rebasing on top of current develop so the commits history is simpler to review ?

**Comment by aminiussi** [comment]
I think I just rebased. But it's the first time I use the command.
Please let me know.

**Comment by aminiussi** [comment]
Github claim I want to merge 7 commit, but the diff only show changes associated with be0f63e...

**Comment by jfalcou** [comment]
I think you can do a git rebase -i develop  and manually remove the duplicate commits. My intuition says that only be0f63e is useful no ?

**Pull request closed without merging**
