### PR TITLE
Remove ';' from BOOST_SIMD_DEFINE_PACK_TRAITS macro which gives an er…

### PR DESCRIPTION
**Pull request by alankelly**
…ror when compiled with -Wpedantic

### CODE REVIEW

**Comment by ccharly** [comment]
well... I would rather prefer to remove the extra semi-colon inside the macro instead than removing it everywhere we're calling it.

It's a good practice to use the semi-colon when calling the macro instead of assuming that there is one. Also, this helps editors to not break indentations when using autoindentation for example. (`gg=G` in vim for example). Can you do that instead?

**Comment by jfalcou** [comment]
I concur. Change the macro instead.

**Comment by alankelly** [comment]
OK, that's fixed. However, we have the same problem with  BOOST_DISPATCH_FUNCTION_DECLARATION

which declares a function, when a semi-colon is placed after this macro call, we get the same error (again pedantic)
In this case, there is no semi-colon in the macro to remove, can you suggest a way of fixing this?

**Comment by jfalcou** [comment]
The semicolon here is mostly for IDE to not vomit crap. Not sure what to do beside removing it indeed.

**Comment by ccharly** [comment]
yes.. indeed if it's a function we have no other choice I guess...anyway, thanks for the quick fix, just wait for travis and we'll merge that.

**Comment by alankelly** [comment]
"The job exceeded the maximum time limit for jobs, and has been terminated."

It's a timeout, I think this is safe to merge, any objections?

**Comment by ccharly** [comment]
that's fine. I'll merge. :)

**Pull request merged**
