### PR TITLE
Hidden var warning

### PR DESCRIPTION
**Pull request by aminiussi**
Found a few other. Since they're warning, they only show up when recompiled (and when they reach some visibility between the other messages).

### CODE REVIEW

**Comment by aminiussi** [comment]
This issue appears to make #412 obsolete.

**Comment by aminiussi** [comment]
Oups, commented on the wrong PR, this is not connected to #420 at all.

**Comment by jfalcou** [comment]
Isn't `exponent ` a name tough ? `expo` is probably better and enough

**Comment by aminiussi** [comment]
Renaming done.

**Pull request merged**
