### PR TITLE
user literal fixes

### PR DESCRIPTION
**Pull request by aminiussi**
De activate user defined literal test on platforms with no user defined literals.
rename litteral to literal.

### CODE REVIEW

**Comment by aminiussi** [comment]
Wait, missed one include.

**Comment by aminiussi** [comment]
Should be ok

**Comment by jfalcou** [comment]
I think the ifdef is too broad (as in coverign too much code) as it removes the test on static but not using literal version of insert/extract. I think you only need to protect the void test_lt(Env& $) version of the test by removing it altogether instead of having a STF_PASS.

**Comment by aminiussi** [comment]
Ok, got the parsing right :-)

**Comment by aminiussi** [comment]
Looks better now.

**Pull request merged**
