### PR TITLE
More doc typos1

### PR DESCRIPTION
**Pull request by jtlap**
I have also added a tutorial algorithm page

### CODE REVIEW

**Comment by jfalcou** [comment]
Rebase and amends the documentation and example to take care of the new reduce/transform reduce thing

**Comment by jtlap** [comment]
ok I'll do it as soon as possible

**Comment by jtlap** [comment]
travis time out

**Comment by jtlap** [comment]
what is still preventing from merge ?

**Comment by jfalcou** [comment]
@alankelly should make a proof reading then we merge

**Pull request closed without merging**
