### PR TITLE
One more make -> detail::make 'coz of intel15

### PR DESCRIPTION
**Pull request by aminiussi**
Business as usual... ;-)

### CODE REVIEW

**Comment by jfalcou** [comment]
Does make<T>(x,...,z) even works outside those cases or is it completely unusable on icpc15 ?

**Comment by aminiussi** [comment]
There are a few left in test cpp files, need to check if they actually compile.

**Comment by aminiussi** [comment]
The ones in test/function/simd/make/arithmetic.cpp and test/function/simd/make/logical.cpp looks ok.

> Built target function.simd.make.logical.unit
> Built target function.simd.make.arithmetic.unit

> [alainm@r428 intel15]$ ctest -R function.simd.make
> Test project /scratch/alainm/view/boost.simd/intel15
>     Start 1353: function.simd.make.arithmetic.unit
> 1/2 Test #1353: function.simd.make.arithmetic.unit ...   Passed    0.14 sec
>     Start 1354: function.simd.make.logical.unit
> 2/2 Test #1354: function.simd.make.logical.unit ......   Passed    0.12 sec
> 
> 100% tests passed, 0 tests failed out of 2
> 
> Total Test time (real) =   9.13 sec
> [alainm@r428 intel15]$ 

but why ? except for the fact that they are "directly" instantiated...

**Comment by jfalcou** [comment]
Didn't you changed the test for make to use detail:: ??

**Comment by aminiussi** [comment]
Some of them, on a fix and fail basis, the ones in
test/api/pack/ctor/list.cpp
test/function/simd/make/arithmetic.cpp
test/function/simd/make/logical.cpp
are still bs::make
I can change all of them for uniformity if that's better, or keep the ones that seems to work with intel15 for future examination.

**Comment by jfalcou** [comment]
OK

What about making make behave like constant and have a proper non-detail overload that do  `make(as(x),t...)` ? so we have a non-detail public way to make it work ?

**Comment by jfalcou** [comment]
Can you give a go to the explicit_make branch and see if its new syntax helps. It's basically the same than in detail, except not in detail so it's less awkward.

**Comment by aminiussi** [comment]
I'll give it a try tomorow. Thanks.

**Pull request closed without merging**
