### PR TITLE
Fix #17 - Implement cast<T> fonction across pack

### LINKED ISSUE #17: type casts for boost.simd types
it would be great to be able to cast between packs (or other boost.simd types) of the same size with an API function ... e.g. from `pack<float, N>` to `pack<double, N>`

### PR DESCRIPTION
**Pull request by jfalcou**
Propose a new function `cast` that enables casting between scalar and pack type with same cardinal.

Exemple usage:

`
  pack<float,4> x{1,2,3,4};
  pack<int32_t,4> y = cast<int32_t>(x);
`

Most common cases are optimized and cases implementable as splice/comben are also supported.

### CODE REVIEW

**Comment by kamirr** [comment]
Wouldn't it be better to name it `pack_cast`? `cast` is quite ambigous, even in `boost::simd` namespace, especially if it takes integral type instead of whole pack as template parameter.

**Comment by jfalcou** [comment]
I would prefer `simd_cast` then. What do you think ?

**Comment by kamirr** [comment]
Ok IMHO, I won't be wondering "what did that code do?". :grin:

**Comment by ccharly** [comment]
well... `pack_cast` would follow the same scheme than `pack_traits` and other `pack_*` files. Also, `simd_cast` could be ambiguous with "raw" simd vectors don't you think? I do prefer `pack_cast`. :)

**Comment by jfalcou** [comment]
so `pack_cast ` it is

**Pull request merged**
