### PR TITLE
Doc

### PR DESCRIPTION
**Pull request by alankelly**

### CODE REVIEW

**Comment by jfalcou** [comment]
This needs ot be rebased as it contains exisiting charly's commit

**Comment by ccharly** [comment]
I'm modifying the doxygen template right now and that's pretty heavy again. I do need to merge this before. I'm gonna rebase and merge it shortly.

**Comment by alankelly** [comment]
VERBATIM_HEADERS       = NO
MATHJAX_FORMAT         = SVG

These are the only two changes to Doxyfie.in, everything should merge without a problem

**Comment by ccharly** [comment]
Ah no, I didn't mean your changes were heavy, I was saying that mines were (but not visible right now). We still need to rebase this branch to the most recent HEAD of develop though. Can you do it and push forced here? Also, we could probably squash them when rebasing will be done.

I can do it if you want.

**Comment by alankelly** [comment]
I rebased this morning, no commits since then, so it should be good to go

**Comment by ccharly** [comment]
my bad, didn't see that. :) Let merge that then, thanks!

**Pull request merged**
