### PR TITLE
using permutevar8x32 for some lookup dispatches

### PR DESCRIPTION
**Pull request by jtlap**
Is there a reason not to use these intrinsics ?

Also I was not able to test the commit. Travis will tell...

### CODE REVIEW

**Comment by jfalcou** [comment]
_mm256_permutevar_pd only works with sub 128bits lane : 

IF (b[1] == 0) dst[63:0] := a[63:0]
IF (b[1] == 1) dst[63:0] := a[127:64]
IF (b[65] == 0) dst[127:64] := a[63:0]
IF (b[65] == 1) dst[127:64] := a[127:64]
IF (b[129] == 0) dst[191:128] := a[191:128]
IF (b[129] == 1) dst[191:128] := a[255:192]
IF (b[193] == 0) dst[255:192] := a[191:128]
IF (b[193] == 1) dst[255:192] := a[255:192]

lookup is able to move everything anywhere so it wont work.

**Comment by jtlap** [comment]
I speak here of permutevar8x32... not of permutevar_pd or ps
__m256 _mm256_permutevar8x32_ps (__m256 a, __m256i idx))
and 
__m256i _mm256_permutevar8x32_epi32 (__m256i a, __m256i idx)
for instance
Description
Shuffle single-precision (32-bit) floating-point elements in a across lanes using the corresponding index in idx.
Operation
FOR j := 0 to 7
	i := j*32
	id := idx[i+2:i]*32
	dst[i+31:i] := a[id+31:id]
ENDFOR
dst[MAX:256] := 0

**Comment by jtlap** [comment]
It seems know to compile except for N/2

**Comment by jfalcou** [comment]
1/ we're in 2017 ;)
2/ the test is missign the N/2 case and thus are incomplete

**Review by jfalcou — CHANGES_REQUESTED** [review]
Make N/2 tests pass

**Comment by jtlap** [comment]
travis time out

**Review by jfalcou — APPROVED** [review]

**Pull request merged**
